### ISSUE TITLE
Front - Layout - bug au changement de profil

### ISSUE THREAD

**Issue by mickablondo** [mickablondo/Alyra-project3#17]
Si on se connecte en tant que voter, on voit les composants du voter.  
Si on se connecte ensuite en tant qu'owner, les composants de l'owner ET ceux du voter sont présents.  
Si on rafraîchit la page, seuls les composants de l'owner sont visibles.  
  
Il faudrait ne voir que les composants du profil sélectionné sans avoir à recharger la page.

**Comment by alowoa** [comment]
fixe par: https://github.com/mickablondo/Alyra-project3/pull/27
