### ISSUE TITLE
Front - affichage du compte utilisé

### ISSUE THREAD

**Issue by mickablondo** [mickablondo/Alyra-project3#19]
Demandé dans le barème de notation, il faut afficher l'adresse de l'utilisateur connecté

**Comment by alowoa** [comment]
dans https://github.com/mickablondo/Alyra-project3/tree/4-front-composant-head

**Comment by mickablondo** [comment]
C'est top !
![image](https://github.com/mickablondo/Alyra-project3/assets/36310658/c44e5c69-d04a-4001-8c36-31959b242f16)
