### ISSUE TITLE
Back - Solidity

### ISSUE THREAD

**Issue by mickablondo** [mickablondo/Alyra-project3#2]
natspec + ddos gas limit + optimisation + TU

**Comment by alowoa** [comment]
- **Natspec**: ajout de quelque details. j'ai tenté de rajouter solidity-docgen mais avec truffle une vrai galère ...
- **TU** ajoute avec fix (tests d'origine en echec avec le genesis proposal)
- **ddos** ce que t'as mis en place est ok pr moi
- **optimization**: quelques unes de faites cf readme, par contre j'ai pas changé tt les require en revert+ custom error, j'ai juste laisse une note dans le readme
