### ISSUE TITLE
Front - recharger la page au changement de compte metamask

### ISSUE THREAD

**Issue by mickablondo** [mickablondo/Alyra-project3#22]

**Comment by alowoa** [comment]
- refresh la page au changement de networkd  si au prealable un compte a pu etre recupere:
- reset des etats dans le cas du account changes au lieux du reload de tt la page. en fait la recommandation ne porte que sur le changement de compte je m'etais trompe (cf: https://docs.metamask.io/wallet/reference/provider-api/  )
