### ISSUE TITLE
Winning proposal

### ISSUE THREAD

**Issue by mickablondo** [mickablondo/Alyra-project3#31]
description à afficher au milieu une fois le vote terminé

**Comment by alowoa** [comment]
A noter que pr tester jusqu'au bout j'ai rajoute un winning pannel a droite, 
donc peut etre partir de celui la pr le deplacer
![image](https://github.com/mickablondo/Alyra-project3/assets/2265208/a9c368f4-c71f-4bd7-9c01-ec531950a08f)
![image](https://github.com/mickablondo/Alyra-project3/assets/2265208/f5fb200b-d58d-4a4f-b216-1883fae08b2c)
![image](https://github.com/mickablondo/Alyra-project3/assets/2265208/0f42a60f-d675-422f-b6d6-d161367d2e08)
