### ISSUE TITLE
Front - live update bug sur participation

### ISSUE THREAD

**Issue by alowoa** [mickablondo/Alyra-project3#42]
Dans Global Participation:
- [x]  global participation
- [x]  has voted 

Dans wining proposal
- [x] Votes

![Screenshot 2023-07-01 at 11 46 50](https://github.com/mickablondo/Alyra-project3/assets/2265208/eb4e8f18-6fcd-44a9-95c0-56b0d998cf39)

**Comment by mickablondo** [comment]
- [x] Données non remontées pour the owner :
  
![image](https://github.com/mickablondo/Alyra-project3/assets/36310658/f716e67a-d126-490b-b9b3-c2cede983aa6)
Alors que pour le voter :  
![image](https://github.com/mickablondo/Alyra-project3/assets/36310658/95e7c171-7df4-432c-926f-60a9d9afd644)
