### ISSUE TITLE
Front - Données non remontées pour the owner

### ISSUE THREAD

**Issue by mickablondo** [mickablondo/Alyra-project3#46]
Données non remontées pour the owner :
  
![image](https://github.com/mickablondo/Alyra-project3/assets/36310658/f716e67a-d126-490b-b9b3-c2cede983aa6)
Alors que pour le voter :  
![image](https://github.com/mickablondo/Alyra-project3/assets/36310658/95e7c171-7df4-432c-926f-60a9d9afd644)

Suspicion : getOneProposal => onlyVoters !
Peut-être proposer juste l'id de la winning proposal (comme pour les visitor d'ailleurs car donnée publique)

**Comment by alowoa** [comment]
yes on pourrait utiliser isvoting state comme check avant l'appel a droit limite
sinon renvoyer un objet par default avec N/A par exemple sr les champs non recuperable ...

**Comment by mickablondo** [comment]
A voir demain, j'ai des problèmes pour savoir si la personne est voter ou non.
Pb plus particulièrement dans winningProposal et dans ProposalList pour récupérer la description.
Il faut que je fasse le getOneProposal au chargement de ces pages de l'ensemble des proposalId pour ProposalList et de la winningProposalId pour le composant WinningProposal.

**Comment by mickablondo** [comment]
Ce qui a été fait : 
 - ne pas récupérer la description de la proposal dans l'index car si owner connecté alors reçoit des revert ;
 - liste d'id des proposals dans l'index pour les donner aux sous-composants : winning, proposalList, votingState
 - pas de modif dans votingState car le composant n'utilise que tableau.length
 - modif effectuée avec succès sur le winning : owner et visitor ne voient que l'id, les voters voient toutes les infos
 - Erreur sur ProposalList ... : soit boucle infinie soit affichage aléatoire des propositions
