### ISSUE TITLE
Front - composant proposal add 

### ISSUE THREAD

**Issue by alowoa** [mickablondo/Alyra-project3#7]

**Comment by mickablondo** [comment]
Fonctionnalités réalisées :  
- ajout bouton add
- liste les propositions ajoutées (via les events)
- grise le bouton si l'état du workflow n'est pas le bon (création d'une Enum)
- vide le contenu du textarea après avoir ajouté la proposition
  
![image](https://github.com/mickablondo/Alyra-project3/assets/36310658/6cb08c5c-2d7d-40eb-baf1-3c08bdeebdea)

**Comment by mickablondo** [comment]
Ajout des events proposal dans index.js
